---
title: "Data_import"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
## can use library(janitor) or ::janitor below
```

## import FAS csv file

Import my first csv. 

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
```

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```

## look at data

Look at litters data.
```{r}
head(litters_data)
tail(litters_data)

skimr::skim(litters_data)

## View(litters_data) lets you view data tables, but cannot use knit function (type in console)
```

Skip some rows; omit variable names.

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  skip = 10, col_names = FALSE)
```

Look at pups data
```{r}
head(pups_data)
tail(pups_data)

skimr::skim(pups_data)
pups_data = janitor::clean_names(pups_data)
pups_data = read_csv(file = "./data/FAS_pups.csv",
  col_types = "ciiii"
)
litters_data
```

## other formats

Read in mlb data
```{r}
mlb_data = readxl::read_excel(path = ".data/mlb11.xlsx")

##subset of excel file
mlb_subset = readxl::read_excel(path = ".data/mlb11.xlsx",
                                range = "A1:E17")
```

Read in pulse data:

```{r}
pulse_data = haven::read_sas(".data/public_pulse_data.sas7bdat")
view(pulse_data)
```

## compare with base R
```{r}
pups_readr = read_csv(".data/FAS_pups.csv")
pups_baser = read.csv(".data/FAS_pups.csv")

pups_readr
pups_baser

##generally, stick with read R
```

