---
title: "Data Manipulation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
## can use library(janitor) or ::janitor below
```

## import FAS csv file

Import my first csv. 

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
```

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```

## look at data

Look at litters data.
```{r}
head(litters_data)
tail(litters_data)

skimr::skim(litters_data)

## View(litters_data) lets you view data tables, but cannot use knit function (type in console)
```

Skip some rows; omit variable names.

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  skip = 10, col_names = FALSE)
```

Look at pups data
```{r}
head(pups_data)
tail(pups_data)

skimr::skim(pups_data)
pups_data = janitor::clean_names(pups_data)
pups_data = read_csv(file = "./data/FAS_pups.csv",
  col_types = "ciiii"
)
litters_data
```

## other formats

Read in mlb data
```{r eval=FALSE}
mlb_data = readxl::read_excel(path = ".data/mlb11.xlsx")

##subset of excel file
mlb_subset = readxl::read_excel(path = ".data/mlb11.xlsx",
                                range = "A1:E17")
```

Read in pulse data:

```{r eval=FALSE}
pulse_data = haven::read_sas(".data/public_pulse_data.sas7bdat")
view(pulse_data)
```

## compare with base R
```{r}
pups_readr = read_csv(".data/FAS_pups.csv")
pups_baser = read.csv(".data/FAS_pups.csv")

pups_readr
pups_baser

##generally, stick with read R
```

##select variables
```{r}
select(litters_data, group, litter_number, gd0_weight)
```

...specify range of data
```{r}
select(litters_data, group, gd_of_birth::pups_survive)
```

...by saying what variables you want to remove
```{r}
select(litters_data, -litter_number)
```

...select variabes and rename in the same step
```{r}
select(litters_data, group, litter_number, gest_day_0_weight = gd0_weight)

##or use 

rename(liters_data, gest_day_0_weight = gd0_weight)
```

## filter observations 
```{r}
filter(litters_data, gd0_weight < 25)
filter(litters_data, gd0_weight >= 25)

filter(litters_data, pups_born_alive == 8)

##removes observations with missing gd0_weight data
filter(litters_data, !is.na(gd0_weight))

##filters in groups 7 or 8
filter(litters_data, group == "Low8" | group == "Low7")
filter(litters_data, group %in% c("Low7", "Low8"))

filter(litters_data, pups_born_alive %in% 4::6)

filters(litters_data, pups_born_alive, %in% 4:7, }is.na(gd0_weight))
```

##mutate
```{r}
##create variables
mutate(litters_data, 
       wt_gain = gd18_weight - gd0_weight,
       group = tolower(group)
       )

##create new variable, and then square variable immediately
mutate(litters_data, 
       wt_gain = gd18_weight - gd0_weight,
       wt_gain_squared = wt_gain^2)
```


